//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrakBanking.ThirdPartyIntegration.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResetPin(string serialNumber, string applicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ResetPinAsync(string serialNumber, string applicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetPin(string serialNumber, string applicationName, string newPIN, string confirmNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetPinAsync(string serialNumber, string applicationName, string newPIN, string confirmNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetTokenActivation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResetTokenActivation(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetTokenActivation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ResetTokenActivationAsync(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthoriseUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AuthoriseUser(string domain, string userID, string pin, string dpResponse, string password, bool reqHostCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthoriseUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AuthoriseUserAsync(string domain, string userID, string pin, string dpResponse, string password, bool reqHostCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangePin(string domain, string userID, string pin, string dpResponse, string newPIN, string confirmNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChangePinAsync(string domain, string userID, string pin, string dpResponse, string newPIN, string confirmNewPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignTokenToUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AssignTokenToUser(string domain, string serialNumber, string userID, string gracePeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignTokenToUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AssignTokenToUserAsync(string domain, string serialNumber, string userID, string gracePeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnassignToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UnassignToken(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnassignToken", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UnassignTokenAsync(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateUser(string userid, string domain, string orgunit, string username, string desc, string email, string phone, string mobile, string pwd, string isDiable, string isLocked, string local_auth, string back_auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateUserAsync(string userid, string domain, string orgunit, string username, string desc, string email, string phone, string mobile, string pwd, string isDiable, string isLocked, string local_auth, string back_auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnableUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EnableUser(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnableUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EnableUserAsync(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisableUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DisableUser(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisableUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DisableUserAsync(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LinkUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LinkUser(string domain, string userID, string useDPFromUserDomain, string useDPFromUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LinkUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LinkUserAsync(string domain, string userID, string useDPFromUserDomain, string useDPFromUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlinkUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UnlinkUser(string domain, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlinkUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UnlinkUserAsync(string domain, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckUser(string domain, string userID, string toUserID, string orgUnit, string disabled, string locked, string hasDP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckUserAsync(string domain, string userID, string toUserID, string orgUnit, string disabled, string locked, string hasDP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TokenExist(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenExist", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TokenExistAsync(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlockUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UnlockUser(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlockUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UnlockUserAsync(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteUser(string domain, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(string domain, string userid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : FinTrakBanking.ThirdPartyIntegration.Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<FinTrakBanking.ThirdPartyIntegration.Service.ServiceSoap>, FinTrakBanking.ThirdPartyIntegration.Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ResetPin(string serialNumber, string applicationName) {
            return base.Channel.ResetPin(serialNumber, applicationName);
        }
        
        public System.Threading.Tasks.Task<string> ResetPinAsync(string serialNumber, string applicationName) {
            return base.Channel.ResetPinAsync(serialNumber, applicationName);
        }
        
        public string SetPin(string serialNumber, string applicationName, string newPIN, string confirmNewPIN) {
            return base.Channel.SetPin(serialNumber, applicationName, newPIN, confirmNewPIN);
        }
        
        public System.Threading.Tasks.Task<string> SetPinAsync(string serialNumber, string applicationName, string newPIN, string confirmNewPIN) {
            return base.Channel.SetPinAsync(serialNumber, applicationName, newPIN, confirmNewPIN);
        }
        
        public string ResetTokenActivation(string serialNumber) {
            return base.Channel.ResetTokenActivation(serialNumber);
        }
        
        public System.Threading.Tasks.Task<string> ResetTokenActivationAsync(string serialNumber) {
            return base.Channel.ResetTokenActivationAsync(serialNumber);
        }
        
        public string AuthoriseUser(string domain, string userID, string pin, string dpResponse, string password, bool reqHostCode) {
            return base.Channel.AuthoriseUser(domain, userID, pin, dpResponse, password, reqHostCode);
        }
        
        public System.Threading.Tasks.Task<string> AuthoriseUserAsync(string domain, string userID, string pin, string dpResponse, string password, bool reqHostCode) {
            return base.Channel.AuthoriseUserAsync(domain, userID, pin, dpResponse, password, reqHostCode);
        }
        
        public string ChangePin(string domain, string userID, string pin, string dpResponse, string newPIN, string confirmNewPIN) {
            return base.Channel.ChangePin(domain, userID, pin, dpResponse, newPIN, confirmNewPIN);
        }
        
        public System.Threading.Tasks.Task<string> ChangePinAsync(string domain, string userID, string pin, string dpResponse, string newPIN, string confirmNewPIN) {
            return base.Channel.ChangePinAsync(domain, userID, pin, dpResponse, newPIN, confirmNewPIN);
        }
        
        public string AssignTokenToUser(string domain, string serialNumber, string userID, string gracePeriod) {
            return base.Channel.AssignTokenToUser(domain, serialNumber, userID, gracePeriod);
        }
        
        public System.Threading.Tasks.Task<string> AssignTokenToUserAsync(string domain, string serialNumber, string userID, string gracePeriod) {
            return base.Channel.AssignTokenToUserAsync(domain, serialNumber, userID, gracePeriod);
        }
        
        public string UnassignToken(string serialNumber) {
            return base.Channel.UnassignToken(serialNumber);
        }
        
        public System.Threading.Tasks.Task<string> UnassignTokenAsync(string serialNumber) {
            return base.Channel.UnassignTokenAsync(serialNumber);
        }
        
        public string CreateUser(string userid, string domain, string orgunit, string username, string desc, string email, string phone, string mobile, string pwd, string isDiable, string isLocked, string local_auth, string back_auth) {
            return base.Channel.CreateUser(userid, domain, orgunit, username, desc, email, phone, mobile, pwd, isDiable, isLocked, local_auth, back_auth);
        }
        
        public System.Threading.Tasks.Task<string> CreateUserAsync(string userid, string domain, string orgunit, string username, string desc, string email, string phone, string mobile, string pwd, string isDiable, string isLocked, string local_auth, string back_auth) {
            return base.Channel.CreateUserAsync(userid, domain, orgunit, username, desc, email, phone, mobile, pwd, isDiable, isLocked, local_auth, back_auth);
        }
        
        public string EnableUser(string domain, string userid) {
            return base.Channel.EnableUser(domain, userid);
        }
        
        public System.Threading.Tasks.Task<string> EnableUserAsync(string domain, string userid) {
            return base.Channel.EnableUserAsync(domain, userid);
        }
        
        public string DisableUser(string domain, string userid) {
            return base.Channel.DisableUser(domain, userid);
        }
        
        public System.Threading.Tasks.Task<string> DisableUserAsync(string domain, string userid) {
            return base.Channel.DisableUserAsync(domain, userid);
        }
        
        public string LinkUser(string domain, string userID, string useDPFromUserDomain, string useDPFromUserID) {
            return base.Channel.LinkUser(domain, userID, useDPFromUserDomain, useDPFromUserID);
        }
        
        public System.Threading.Tasks.Task<string> LinkUserAsync(string domain, string userID, string useDPFromUserDomain, string useDPFromUserID) {
            return base.Channel.LinkUserAsync(domain, userID, useDPFromUserDomain, useDPFromUserID);
        }
        
        public string UnlinkUser(string domain, string userID) {
            return base.Channel.UnlinkUser(domain, userID);
        }
        
        public System.Threading.Tasks.Task<string> UnlinkUserAsync(string domain, string userID) {
            return base.Channel.UnlinkUserAsync(domain, userID);
        }
        
        public string CheckUser(string domain, string userID, string toUserID, string orgUnit, string disabled, string locked, string hasDP) {
            return base.Channel.CheckUser(domain, userID, toUserID, orgUnit, disabled, locked, hasDP);
        }
        
        public System.Threading.Tasks.Task<string> CheckUserAsync(string domain, string userID, string toUserID, string orgUnit, string disabled, string locked, string hasDP) {
            return base.Channel.CheckUserAsync(domain, userID, toUserID, orgUnit, disabled, locked, hasDP);
        }
        
        public string TokenExist(string serialNumber) {
            return base.Channel.TokenExist(serialNumber);
        }
        
        public System.Threading.Tasks.Task<string> TokenExistAsync(string serialNumber) {
            return base.Channel.TokenExistAsync(serialNumber);
        }
        
        public string UnlockUser(string domain, string userid) {
            return base.Channel.UnlockUser(domain, userid);
        }
        
        public System.Threading.Tasks.Task<string> UnlockUserAsync(string domain, string userid) {
            return base.Channel.UnlockUserAsync(domain, userid);
        }
        
        public string DeleteUser(string domain, string userid) {
            return base.Channel.DeleteUser(domain, userid);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(string domain, string userid) {
            return base.Channel.DeleteUserAsync(domain, userid);
        }
    }
}
