<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.0.0" />
    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="3.6.0" />
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="106.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FintrakBanking.Entities\FintrakBanking.Entities.csproj" />
    <ProjectReference Include="..\FintrakBanking.ViewModels\FintrakBanking.ViewModels.csproj" />
  </ItemGroup>

</Project>
