using FintrakBanking.Common;
using FintrakBanking.Common.Enum;
using FintrakBanking.ViewModels;
using FintrakBanking.ViewModels.WorkFlow;
using FintrakBanking.ViewModels.Credit;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.Linq;
using FintrakBanking.Entities.Models;
using FintrakBanking.ViewModels.Setups.General;
using FintrakBanking.Interfaces.WorkFlow;
using FintrakBanking.ViewModels.Customer;
using FintrakBanking.ViewModels.ThridPartyIntegration;
using FintrakBanking.ViewModels.Finance;

namespace FintrakBanking.Interfaces.Credit
{
    public interface ILoanApplicationRepository
    {
        Task<IEnumerable<RetailRecoveryCustomerTransactionsViewModels>> GetRetailRecoveryReporting(DateTime startDate, DateTime endDate, int accreditedConsultantId, string customer);
        Task<bool> UpdateLoanApplicationTagsLMS(LoanApplicationTagsLMSViewModel model, int id, UserInfo user);
        Task<LoanApplicationTagsLMSViewModel> GetLoanApplicationTagsLMS(int id);
        Task<IQueryable<LoanReviewApplicationViewModel>> GetRejectedReviewLoanApplications(UserInfo user);
        Task<IQueryable<LoanApplicationViewModel>> GetRejectedLoanApplicationsArch(UserInfo user);
        Task<List<LoanApplicationDetailViewModel>> GetLoanApplicationDetailsById(int loanApplicationId, int companyId);
        Task<List<LoanApplicationDetailViewModel>> GetLmsLoanApplicationDetailsById(int loanApplicationId, int companyId);
        Task<IEnumerable<jobLoanApplicationDetailViewModel>> GetLoanApplicationDetailById(int loanApplicationDetailId, int companyId);
        Task<IEnumerable<LoanApplicationDetailViewModel>> GetAllLoanApplicationsDetailsById(int loanApplicationId, int companyId);
        Task<IEnumerable<jobLoanApplicationDetailViewModel>> GetLoanApplicationDetailByLoanApplicationId(int loanApplicationId, int companyId);
        Task<bool> CheckExistingCertificateOfOwnership(string certificateOfOwnership, int companyId);
        Task<IEnumerable<ExistingLoanApplicationViewModel>> ExistingLoanApplication(int customerId, int companyId);
        CurrencyExchangeRateViewModel GetExchangeRate(DateTime date, short currencyId, int companyId);
        Task<IEnumerable<LoanApplicationViewModel>> GetAllLoanApplications(int companyId);
        Task<IEnumerable<LoanApplicationViewModel>> GetLoanApplicationById(int loanApplicationId, int companyId);
        Task<IEnumerable<ProductClassViewModel>> GetProductClass();
        Task<IEnumerable<CustomerViewModels>> GetCustomerByApplicationId(int applicationId, string processtype);
        Task<CustomerApplicationTransactionsViewModels> GetCustomerTransactions(int customerId, int applicationId, bool islms);
        Task<LoanApplicationUpdateMessage> UpdateApprovalStatusForApplication(int applicationId, int staffId);
        Task<IEnumerable<dynamic>> GetLoanApplicationByRelationshipOfficerId(int relationshipOfficerId, int companyId);
        bool SendApplicationToEdit(int loanApplicationId, int operationId, int accountOfficerId);
        Task<IEnumerable<LoanApplicationViewModel>> FindLoanApplication(string referenceNumberOrName, int companyId);
        Task<bool> UpdateApprovalStatus(ApprovalViewModel entity);
        Task<IEnumerable<LoanApplicationDetailViewModel>> GetLoanApplicationsDetails(int loanApplicationId, int companyId);
        Task<IQueryable<LoanApplicationDetailViewModel>> GetLoanApplicationsAwaitingCheckList(int companyId);
        Task<List<LoanApplicationViewModel>> Search(string searchString, int staffId = 0);
        Task<List<LoanApplicationViewModel>> SearchDrawDown(string searchString, int staffId = 0);
        Task<List<WorkflowTrackerViewModel>> SearchBookedLoans(int loanApplicationDetailId);
        LoanApplicationViewModel AddLoanApplication( LoanApplicationViewModel loan, bool isExceptionalLoan = false);
        Task<bool> ValidateDuplicateLoanApplication( LoanApplicationViewModel loan);
        string GetRefrenceNumber();
        Task<bool> AddLoanApplicationCollateral(List<LoanApplicationCollateralViewModel> entity);
        Task<IEnumerable<LoanApplicationCollateralViewModel>> GetLoanApplicationCollateral(int loanApplicatioinCollateralId);
        Task<dynamic> GetLoanApplicationDetailsProductProgram(int loanApplicationDetailId);
        Task<ValidateDataViewModel> ValidateDocumentDate(ValidateDataViewModel data);
        Task<ValidateNumberViewModel> ValidateDocumentNumber(ValidateNumberViewModel data);
        Task<IQueryable<LoanApplicationViewModel>> GetLoanApplicationsByOperation(int operationId, int? classId, int branchId, int staffId);
        Task<IQueryable<LoanApplicationViewModel>> GetRejectedLoanApplications(UserInfo user);
        Task<string> ReviewRequest(ForwardViewModel model);
        dynamic GetCollateralRequirements(int applicationID, int? collateralCurrencyId, int companyId);
        Task<bool> UpdateLoanApplicationDetails(LoanApplicationDatailViewModel entity, UserInfo user);
        void LoadCustomerTurnover(int applicationId, int staffId, CustomerTurnoverViewModel model);
        void GetCustomerRatiosFromBasel(int applicationId, int staffId);
        void GetCustomerGroupRatiosFromBasel(int applicationId, int staffId);
        void GetCorporateCustomerRatingFromBasel(int applicationId, int staffId);
        void GetFacilityRatingFromBasel(int applicationId, int staffId);
        void LoadCustomerTurnoverLms(int applicationId, int staffId, CustomerTurnoverViewModel model);
        Task<IEnumerable<ProductFeesViewModel>> GetLoanApplicationFees(int loanDetailId);
        Task<List<FacilityRatingViewModel>> GetFacilityRating(int applicationDetailId);
        Task<short> SubmitLoanApplicationForCam(int applicationId, int staffId, int checkListIndex);
        int? GetFirstAdhocReceiverLevel(int staffId, int operationId, short? productClassId, bool next = false);
        bool ArchiveLoanApplication(int loanAppliactionId, int operationId, short applicationStatus, int archivedBy);
        void ArchiveLoanApplicationDetails(int loanApplicationDetailId);
        int? GetFirstReceiverLevel(int staffId, int operationId, short? productClassId, int? productId, int? exclusiveFlowChangeId, bool next = false);
        Task<int?> GetFirstLevelStaffId(int levelId, int userBranch);
        Task<List<ProductFeeViewModel>> GetLoanApplicationProductFees(int loanApplicationDeatilId);
        Task<bool> ProductFeesConcession(ProductFeesViewModel fees, UserInfo user);
        Task<dynamic> GetLoanAppById(int loanApplicationDetailId, int companyId);
        Task<IEnumerable<LoanApplicationViewModel>> SearchForLoan(string searchString);
        Task<bool> DeleteLoanApplicationDetail(int loanApplicationDetailId);
        Task<bool> DeleteLoanApplication(int loanApplicationId);
        Task<IEnumerable<LoanApplicationViewModel>> GetLoanApplicationDedubeCheck(int customerId, int companyId);
        Task<IEnumerable<CreditApplicationViewModel>> CommitteeCreditApplications(int applicationType, int staffId);
        Task<bool> ValidateInvoiceDetails(ValidateNumberViewModel data);
        Task<List<LoanApplicationViewModel>> GetLoanApplication(string searchQuery);
        WorkflowResponse RerouteWorkflowTarget(ForwardViewModel model);
        WorkflowResponse RouteWorkflowTarget(ForwardViewModel model);
        Task<List<LoanApplicationViewModel>> GetAllRequestsForLoanCancellation(int staffId);
        Task<List<LoanReviewApplicationViewModel>> GetAllLmsRequestsForLoanCancellation(int staffId);
        Task<int> SaveCancelledApplcation(LoanApplicationViewModel data);
        Task<int> SaveLMSCancelledApplcation(LoanReviewApplicationViewModel data);
        Task<LoanApplicationViewModel> ViewLaonApplicationCancellationDetails(LoanApplicationViewModel data);
        Task<LoanReviewApplicationViewModel> ViewLmsLaonApplicationCancellationDetails(LoanReviewApplicationViewModel values);
        Task<bool> GoForLoanApplicationCancellationApproval(LoanApplicationViewModel data);
        Task<bool> GoForLmsLoanApplicationCancellationApproval(LoanReviewApplicationViewModel data);
        Task<List<TransactionDynamicsViewModel>> GetTrnasactionDynamics(int loanApplicationId);
        Task<List<ConditionPrecedentViewModel>> GetConditionPrecidents(int loanApplicationId);
        Task<LoanApplicationViewModel> GetSingleLoanApplicationById(int loanApplicationId, int companyId);
        Task<bool> updateSuggestionsLoanApplicationdetail(LoanApplicationDetailViewModel model);
        Task<LoanApplicationDetailViewModel> GetSingleLoanApplicationsDetails(int loanApplicationDetailId, int companyId);
        Task<IEnumerable<LookupViewModel>> GetAllCRMSRepaymentSource();
        Task<IEnumerable<LookupViewModel>> GetAllCRMSFundingSource();
        Task<IEnumerable<LookupViewModel>> GetAllCRMSRepaymentAgreementType();
        Task<List<ConditionPrecedentViewModel>> GetLMSConditionPrecidents(int loanApplicationId);
        Task<IEnumerable<LookupViewModel>> GetAllSyndicationType();
        Task<IEnumerable<LoanApplicationDetailViewModel>> GetLoanApplicationDetailsByReference(string reference, int companyId);
        Task<IEnumerable<LoanApplicationDetailViewModel>> SearchApprovedLoanApplicationDetails(string reference, int companyId);
        CurrentCustomerExposure GetCurrentCompanyExposure();
        CurrentCustomerExposure GetCurrentCustomerExposure(int customerId);
        String ResponseMessage(WorkflowResponse response, string itemHeading);
        IEnumerable<LoanApplicationDetailViewModel> GetExceptionalLoansForApproval(int staffId);
        Task<WorkflowResponse> GoForApprovalExceptionalLoan(ExceptionalLoanViewModel model);
        Task<LoanApplicationDetailViewModel> GetLoanApplicationDetailFields(int detailId);
        LoanApplicationTagsViewModel GetLoanApplicationTags(int id);
        bool UpdateLoanApplicationTags(LoanApplicationTagsViewModel model, int id, UserInfo user);
        Task<IEnumerable<RevisedProcessFlowModel>> getFacilityApplicationRevisedProcessFlow();
        Task<IEnumerable<RevisedProcessFlowModel>> getFacilityApplicationRevisedProcessFlowByProductClassId(short productClassId, short productId, short productTypeId);
        Task<RevisedProcessFlowModel> getCashCollaterizedProcessFlowBy();
        Task<IEnumerable<LoanApplicationViewModel>> GetFacilityByApplicationId(int loanApplicationId);
        Task<bool> LoanApplicationFlowChange(int loanApplicationId);
        Task<bool> DeleteLoanApplicationThatFailedRAC(int loanApplicationDetailId, int deletedBy);
        Task<LoanApplicationFlowChangeViewModel> GetLoanAppicationFlowChange(int id);
        Task<IEnumerable<LoanApplicationFlowChangeViewModel>> GetLoanApplicationFlowChange();
        Task<bool> AddLoanApplicationFlowChange(LoanApplicationFlowChangeViewModel model);
        Task<bool> UpdateLoanApplicationFlowChange(LoanApplicationFlowChangeViewModel model, int id, UserInfo user);
        Task<bool> DeleteLoanApplicationFlowChange(int id, UserInfo user);
        Task<List<RatingAndRatioViewModel>> GetCustomerRatios(int customerId, int applicationId, bool isLms = false);
        Task<CustomerApplicationTransactionsViewModels> GetCustomerTransactionsByFilterLogic(int customerId, int applicationId, int froma, int to, int fYear, int tYear, bool v);
        List<InvoiceDetailViewModel> GetBulkLoanInvoice(byte[] file, UserInfo user);
        Task<IEnumerable<LoanApplicationViewModel>> LoanSearch(string searchString);
        Task<List<accountsViewModels>> GetCustomerTransactionsAccounts(int customerId, int applicationId, bool isLms = false);
        Task<CustomerApplicationTransactionsViewModels> GetCustomerTransactionsFiltered(int customerId, int applicationId, string accountnumber, int? fromYear, int fromMonth, int? toYear, int toMonth, bool isLms = false);
        Task<IEnumerable<LoanApplicationLienViewModel>> GetLienByApplicationDetailId(int applicationDetailId);
        Task<IEnumerable<LoanApplicationLienViewModel>> GetLienByCollateralId(int collateralId);
        Task<LoanApplicationLienViewModel> GetApplicationDetailLien(int id);
        Task<IEnumerable<LoanApplicationLienViewModel>> GetApplicationDetailLienByAccountNo(string accountNo);
        Task<IEnumerable<LoanApplicationLienViewModel>> GetApplicationDetailLienByIsReleased(bool isReleased);
        Task<IEnumerable<LoanApplicationLienViewModel>> GetApplicationDetailLien();
        Task<bool> AddLoanApplicationDetailLien(LoanApplicationLienViewModel model);
        Task<bool> UpdateLoanApplicationDetailLien(LoanApplicationLienViewModel model, int id, UserInfo user);
        Task<bool> DeleteLoanApplicationDetailLien(int id, UserInfo user);
        RacReturnInfoViewModel SaveRac(RacInformationViewModel rac, int? operationId, int productId, int? productClassId, int targetId, int staffId, int applicationId);
        CurrentCustomerExposure GetTotalBankExposure();
        bool ModifyFacility(FacilityModificationViewModel model, int loanApplicationDetailId);
        Task<IEnumerable<LoanDetailReviewTypeViewModel>> GetAllLoanDetailReviewTypes();
        Task<IEnumerable<ApprovedTradeCycleViewModel>> GetAllApprovedTradeCycles();
        List<CurrentCustomerExposure> GetExposures(TBL_LOAN_APPLICATION loanApplication);
        List<CurrentCustomerExposure> GetCustomerExposure(List<CustomerExposure> customerIds, int companyId, short loantypeId);
    }
}